### PR TITLE
Use implementation independent attributes

### LINKED ISSUE #285: Library fails to build with MSVC because of unrecognized attributes
I have a project which requires building for most major platforms, including Windows using MSVC.
Currently, `intx` fails to build with MSBuild due to this warning (`-Werror`):

```warning C5030: attribute 'gnu::always_inline' is not recognized```

Specifically, my CI is on `MSBuild version 17.4.1+9a89d02ff for .NET Framework`

This issue is fixed by #284

### PR DESCRIPTION
**Pull request by 0xAltCunningham**
Fixes #285.

### CODE REVIEW

**Comment by axic** [comment]
We run four MSVC compiler versions ([see recent builds here](https://ci.appveyor.com/project/chfast/intx/builds/46038063) and they seem to succeed.

What compiler version do you see this problem with? Can you point us to some logs / repository?

**Comment by 0xAltCunningham** [comment]
I'm seeing this problem with MSVC v17.4.1+9a89d02ff.
It's the current version used in GitHub Actions when the `windows-latest` image is selected.
Here's an example of the warning being thrown in a build run:
https://github.com/0xAltCunningham/evmtools/actions/runs/4076238955/jobs/7271225492#step:5:19

**Comment by 0xAltCunningham** [comment]
I got the compiler version wrong on my previous comment, that was just the MSBuild version.

When rerunning the job I realized the compiler version is actually MSVC 19.34.31942.0:

```
-- Building for: Visual Studio 17 2022
-- The CXX compiler identification is MSVC 19.34.31942.0
```

**Comment by 0xAltCunningham** [comment]
Not sure if related, but something else that I think could be the cause of this warning is that I'm using `CXX_STANDARD 20` and `CXX_STANDARD 23`

**Comment by axic** [comment]
Interesting, we do have an MSVC 2022 build. Will need to wait for @chfast, maybe he has some insight.

**Comment by axic** [comment]
@chfast ping

**Comment by chfast** [comment]
We specifically disable this warning because the idea of C++ attributes is to wrap compiler-specific features (so it is expected some attributes are going to be unknown to some compilers). Otherwise, you end up with `#if` hell.
https://github.com/chfast/intx/blob/master/cmake/CableCompilerSettings.cmake#L135-L136

**Comment by chfast** [comment]
This has been fixed by #286. Let me know if this works for you.

**Comment by 0xAltCunningham** [comment]
Hey @chfast, the changes introduced in #286 work for me ([Windows CI run](https://github.com/0xAltCunningham/evmtools/actions/runs/4274676633))! Thanks for taking the time to fix it, and I understand now that adding `#if`s to the functions would be a messy solution.

Thanks @axic as well, for the prompt responses and attention paid to this issue.

**Comment by chfast** [comment]
> I understand now that adding `#if`s to the functions would be a messy solution

I think for intx.hpp this is acceptable. After the change the file should build without any warnings disabled. For intx/test I decided to disable unknown pragma warnings but this should affect users much less.

**Comment by chfast** [comment]
I will make intx release soon.

**Pull request closed without merging**
