### PR TITLE
Fix warning issued by Clang-14 due to the use of bitwise operator ins…

### PR DESCRIPTION
**Pull request by bshastry**
…tead of logical operator in boolean expressions.

See https://clang.llvm.org/docs/ReleaseNotes.html#major-new-features

### CODE REVIEW

**Comment by bshastry** [comment]
Context: Failing build of `intx` 0.2.0 against clang-14 which Solidity depends. See https://github.com/ethereum/solidity/runs/4300234079?check_suite_focus=true#step:4:25652

**Comment by bshastry** [comment]
Please note that I have not actually tried to build this PR with clang-14 so it is not guaranteed to fix the referenced failing build.

**Comment by cameel** [comment]
The actual fix will probably need to be more clever because it looks like the bitwise operators were used for performance:

> /// In all implementations bitwise operators are used instead of logical ones
> /// to avoid branching.

Maybe it would be better to try to disable the warnings instead?

**Comment by bshastry** [comment]
> The actual fix will probably need to be more clever because it looks like the bitwise operators were deliberately used here for performance reasons:
> 
> > /// In all implementations bitwise operators are used instead of logical ones
> > /// to avoid branching.
> 
> Maybe it would be better to try to disable the warnings instead?

Interesting. Yes, disabling warnings sounds reasonable to me. Also, wonder if `static_cast<bool>(a & b)` would get rid of the warning and be performance compliant?

**Comment by cameel** [comment]
The warning comes up because operands are `bool`s so casting the result to `bool` probably won't help, that's too late :) But maybe `static_cast<int>(a) & static_cast<int>(b)` would?

**Comment by bshastry** [comment]
> The warning comes up because operands are `bool`s so casting the result to `bool` probably won't help, that's too late :) But maybe `static_cast<int>(a) & static_cast<int>(b)` would?

Oh right! In the meantime, I figured that Solidity does not pull `intx` directly but somewhat obscurely `Solidity->Hera->Hunter->intx` so as a temporary but quicker fix (since all Solidity PRs are stalled due to this atm), I decided to disable the warning during Hera build. Still testing the latter fix. Will post an update later.

**Comment by axic** [comment]
> Solidity does not pull intx directly but somewhat obscurely Solidity->Hera->Hunter->intx

Why does it pull Hera? IIRC For a static build for fuzzing?

**Comment by bshastry** [comment]
> > Solidity does not pull intx directly but somewhat obscurely Solidity->Hera->Hunter->intx
> 
> Why does it pull Hera? IIRC For a static build for fuzzing?

Yes, for the static build used by the fuzzer because the fuzzer binary is run on Google cloud instances that may not have dependencies installed.

**Review by chfast — COMMENTED** [review]
I cannot reproduce it in clang trunk.
https://godbolt.org/z/5YKovYvTP

The warning documentation mentions "use of bitwise operators with boolean operands which have side effects". So maybe they have fixed the diagnostic because in our case there are no side-effects.

Secondly, if you still have issues with these warnings somewhere, please try to fix it by avoiding implicit conversion to bool. I.e. compare the whole expression to zero, e.g. `((x[0] == y[0]) & (x[1] == y[1])) != 0`.

Finally, I noticed these implementations can be improved by using xor-folding. I will do this in a follow-up PR.

**Comment by bshastry** [comment]
> > > Solidity does not pull intx directly but somewhat obscurely Solidity->Hera->Hunter->intx
> > 
> > 
> > Why does it pull Hera? IIRC For a static build for fuzzing?
> 
> Yes, for the static build used by the fuzzer because the fuzzer binary is run on Google cloud instances that may not have dependencies installed.

Actually, I was wrong about the fuzzer depending on Hera. I removed the dependency and there were no linking errors (see https://github.com/ethereum/solidity/pull/12312/files#diff-5d38e645680fd8087e67a52aafe2b3fc8874b689c1c0c6072f68661a72e937fcL105-L116). So, my guess is that intx was being pulled in unnecessarily.

**Comment by chfast** [comment]
The warning has been fixed in #245.

**Pull request closed without merging**
